#!/bin/bash
# NextDNS Blocker - Cross-platform Log Rotation Setup
# Supports: macOS (Homebrew logrotate + launchd) and Linux (logrotate + cron/systemd)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Detect OS
detect_os() {
    case "$(uname -s)" in
        Darwin*)    echo "macos" ;;
        Linux*)     echo "linux" ;;
        *)          echo "unknown" ;;
    esac
}

OS=$(detect_os)

# Set paths based on OS
if [ "$OS" = "macos" ]; then
    LOG_DIR="$HOME/Library/Application Support/nextdns-blocker/logs"
    # Homebrew paths (Intel vs Apple Silicon)
    if [ -d "/opt/homebrew" ]; then
        HOMEBREW_PREFIX="/opt/homebrew"
    else
        HOMEBREW_PREFIX="/usr/local"
    fi
    LOGROTATE_CONF_DIR="$HOMEBREW_PREFIX/etc/logrotate.d"
    LOGROTATE_CONF="$LOGROTATE_CONF_DIR/nextdns-blocker"
    LAUNCH_AGENTS_DIR="$HOME/Library/LaunchAgents"
else
    LOG_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/nextdns-blocker/logs"
    LOGROTATE_CONF="/etc/logrotate.d/nextdns-blocker"
fi

echo ""
echo "  nextdns-blocker log rotation setup"
echo "  -----------------------------------"
echo "  OS: $OS"
echo ""

# Check for unsupported OS
if [ "$OS" = "unknown" ]; then
    echo "  error: unsupported operating system"
    exit 1
fi

# Step 1: Install logrotate if needed
echo "  [1/3] checking logrotate"
if ! command -v logrotate &> /dev/null; then
    echo "         installing logrotate..."
    if [ "$OS" = "macos" ]; then
        if command -v brew &> /dev/null; then
            brew install logrotate
        else
            echo "  error: Homebrew not found. Install from https://brew.sh"
            exit 1
        fi
    else
        if command -v apt-get &> /dev/null; then
            sudo apt-get install -y logrotate
        elif command -v yum &> /dev/null; then
            sudo yum install -y logrotate
        elif command -v dnf &> /dev/null; then
            sudo dnf install -y logrotate
        else
            echo "  error: no package manager found"
            exit 1
        fi
    fi
fi
echo "         $(logrotate --version 2>&1 | head -1)"

# Step 2: Create and install logrotate config
echo "  [2/3] installing logrotate config"

# Create temp config with expanded paths
TEMP_CONF=$(mktemp)

cat > "$TEMP_CONF" << EOF
# Logrotate configuration for nextdns-blocker
# Auto-generated by setup-logrotate.sh

# Application logs
$LOG_DIR/app.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 0644
    dateext
    dateformat -%Y%m%d
}

# Audit logs (keep longer for security compliance)
$LOG_DIR/audit.log {
    weekly
    rotate 12
    compress
    delaycompress
    missingok
    notifempty
    create 0644
    dateext
    dateformat -%Y%m%d
}

# Sync logs
$LOG_DIR/sync.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 0644
    dateext
    dateformat -%Y%m%d
}

# Watchdog logs
$LOG_DIR/watchdog.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 0644
    dateext
    dateformat -%Y%m%d
}
EOF

if [ "$OS" = "macos" ]; then
    # macOS: Install to Homebrew's logrotate.d directory
    mkdir -p "$LOGROTATE_CONF_DIR"
    cp "$TEMP_CONF" "$LOGROTATE_CONF"
    chmod 644 "$LOGROTATE_CONF"
    echo "         config: $LOGROTATE_CONF"
else
    # Linux: Install to system logrotate.d
    sudo cp "$TEMP_CONF" "$LOGROTATE_CONF"
    sudo chmod 644 "$LOGROTATE_CONF"
    echo "         config: $LOGROTATE_CONF"
fi

rm "$TEMP_CONF"

# Step 3: Setup automatic rotation (OS-specific)
echo "  [3/3] setting up automatic rotation"

if [ "$OS" = "macos" ]; then
    # macOS: Create LaunchAgent for daily logrotate
    LOGROTATE_PLIST="$LAUNCH_AGENTS_DIR/com.nextdns-blocker.logrotate.plist"
    LOGROTATE_PATH=$(command -v logrotate)

    cat > "$LOGROTATE_PLIST" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.nextdns-blocker.logrotate</string>
    <key>ProgramArguments</key>
    <array>
        <string>$LOGROTATE_PATH</string>
        <string>$LOGROTATE_CONF</string>
        <string>--state</string>
        <string>$HOME/.local/share/logrotate.status</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>3</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>$LOG_DIR/logrotate.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/logrotate.log</string>
</dict>
</plist>
EOF

    # Load LaunchAgent
    launchctl unload "$LOGROTATE_PLIST" 2>/dev/null || true
    launchctl load "$LOGROTATE_PLIST"

    echo "         launchd job loaded (runs daily at 3:00 AM)"
else
    # Linux: logrotate is typically run by cron/systemd already
    echo "         using system logrotate (cron/systemd)"
fi

# Test configuration
echo ""
echo "  testing configuration..."
if [ "$OS" = "macos" ]; then
    if logrotate -d "$LOGROTATE_CONF" --state "$HOME/.local/share/logrotate.status" 2>&1 | grep -qi "error"; then
        echo "  warning: logrotate configuration may have errors"
    else
        echo "  configuration valid"
    fi
else
    if sudo logrotate -d "$LOGROTATE_CONF" 2>&1 | grep -qi "error"; then
        echo "  warning: logrotate configuration may have errors"
    else
        echo "  configuration valid"
    fi
fi

# Done
echo ""
echo "  done"
echo ""
echo "  config:  $LOGROTATE_CONF"
echo "  logs:    $LOG_DIR"
echo ""
echo "  rotation schedule:"
echo "    app.log     daily,  7 days retention"
echo "    audit.log   weekly, 12 weeks retention"
echo "    sync.log    daily,  7 days retention"
echo "    watchdog.log daily, 7 days retention"
echo ""
if [ "$OS" = "macos" ]; then
echo "  manual commands:"
echo "    test:   logrotate -d $LOGROTATE_CONF --state ~/.local/share/logrotate.status"
echo "    force:  logrotate -f $LOGROTATE_CONF --state ~/.local/share/logrotate.status"
echo ""
else
echo "  manual commands:"
echo "    test:   sudo logrotate -d $LOGROTATE_CONF"
echo "    force:  sudo logrotate -f $LOGROTATE_CONF"
echo ""
fi
